# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ozpau.github.io',
                'doc_host': 'https://ozpau.github.io',
                'git_url': 'https://github.com/ozpau/ozpau.github.io',
                'lib_path': 'ozpau'},
  'syms': {'ozpau.core': {'ozpau.core.foo': ('core.html#foo', 'ozpau/core.py')}}}
